### ISSUE TITLE
Deleted Entries from Dynamic Tables are showing (Custom System Builder)

### ISSUE THREAD

**Issue by ghufufin** [illandril/FoundryVTT-token-tooltips#100]
**Describe the bug**
The tooltip shows deleted entries from a dynamic table and does not show new entries.

**What steps did you take before experiencing the problem?**
1. Enabled tooltips to show entries from a dynamic table
2. Deleted them from the table
3. They still show up
4. Tried writing new entries
5. The new entries don't show up

**What did you expect to happen?**
I expected it not to show deleted entries into a dynamic table and to display new entries when they were made. 

**What happened instead?**
It shows deleted entries and does not show new entries

**Foundry Versions**
Foundry Version 11.315
Custom System Builder 3.0.0

**What other modules did you have active when experiencing this issue (include both names and versions)?**
Add the name and version of any other modules you had active when you experienced this issue. If you are able, please try to reproduce the issue with the least number of other modules active as possible, to help narrow down the specific cause of the problem in case the problem is caused by a conflict between modules.
### Active Modules
Actor Sheet Macro v1.6
Advanced Drawing Tools v2.1.0 [Bugs URL](https://github.com/dev7355608/advanced-drawing-tools/issues)
Better Roll Tables v2.0.34 [Bugs URL](https://github.com/p4535992/foundryvtt-better-rolltables/issues)
Border Control vv2.1.4 [Bugs URL](https://github.com/p4535992/foundryvtt-border-control/issues)
Card Hand Mini Toolbar v1.4.2
Chat GIFs vv1.1.0
Chat Portrait v0.9.4 [Bugs URL](https://github.com/p4535992/foundryvtt-chat-portrait/issues)
Chat Reactions vv2.3.4
Clipboard Image v0.3.2
Combat Chat v1.1.1
Combat Initiative Modifier v1.2.3
Combat Tracker Effect Tooltips v11.0.0 [Bugs URL](https://github.com/dor-fvtt-released-modules/combat-tracker-effect-tooltips/issues)
Custom CSS v2.2.2 [Bugs URL](https://github.com/cswendrowski/FoundryVTT-Custom-CSS/issues)
DFreds Chat Pins v3.0.0 [Bugs URL](https://github.com/DFreds/dfreds-chat-pins/issues)
DFreds Effects Panel v3.1.0 [Bugs URL](https://github.com/DFreds/dfreds-effects-panel/issues)
Dice So Nice! v4.6.9 [Bugs URL](https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/issues)
Arka Stream for Dice So Nice v0.0.1
Cosmic Dice v1.0.1
Entice with Dice so Nice v0.1.0
Fudge O' Plenty v1.0.0
Lordu's Custom Dice for Dice So Nice v0.39
More Bennies - SWADE v0.2.6
Talis Dice v1.0.6
WikiRole for Dice So Nice v0.0.1
Discord Speaking Status v1.2.5
Easy Notes v1.0.1
Forien's Quest Log v0.7.12 [Bugs URL](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/issues)
Gaming Table Player v1.0.5
GM Notes v8.9
Hourglass v1.7.0
Icon Picker v10.3 [Bugs URL](https://github.com/teroparvinen/foundry-icon-picker/issues)
Illandril's Token Tooltips v3.9.0 [Bugs URL](https://github.com/illandril/FoundryVTT-token-tooltips/issues)
Inline Webviewer v3.4.4
Item Macro v1.10.5 [Bugs URL](https://github.com/Foundry-Workshop/Item-Macro/issues)
Keikaku - To-Do List vv0.3.1 [Bugs URL](https://github.com/pyrige/fvtt-keikaku/issues)
Chat Commander v2.0.1 [Bugs URL](https://gitlab.com/woodentavern/foundryvtt-chat-command-lib/-/issues)
CodeMirror v5.58.3-fvtt5
lib - Color Settings v3.0.2
libWrapper v1.12.13.0 [Bugs URL](https://github.com/ruipin/fvtt-lib-wrapper/issues)
Settings Extender v1.2.2
socketlib v1.0.13 [Bugs URL](https://github.com/manuelVo/foundryvtt-socketlib/issues)
Module Management+ v2.2.3 [Bugs URL](https://github.com/mouse0270/module-credits/issues)
Monk's Active Tile Triggers v11.20 [Bugs URL](https://github.com/ironmonk88/monks-active-tiles/issues)
Monk's Bloodsplats v11.12 [Bugs URL](https://github.com/ironmonk88/monks-bloodsplats/issues)
Monk's Chat Timer v11.01 [Bugs URL](https://github.com/ironmonk88/monks-chat-timer/issues)
🎣 Obligatory Fishing Minigame v1.1.1
Party Resources v1.6.0
PopOut! v2.14 [Bugs URL](https://github.com/League-of-Foundry-Developers/fvtt-module-popout/issues)
Portrait box v0.4.8
Scene Spin Transition v1.2.0
Sheet Commander v10.1 [Bugs URL](https://github.com/teroparvinen/foundry-sheet-commander/issues)
Show Notes v11.2
Sticky Notes v1.1.0
Sweet Nothings v1.5.0 [Bugs URL](https://gitlab.com/geekswordsman/sweetnothings/-/issues)
Tabbed Chatlog v1.6.4
The Forge v1.14.9
The Forge: More Awesomeness v1.1
Tile Scroll v2.2
Token Attacher vv4.5.15
Token Color Marker v3.0.2
Token Frames v1.6.3 [Bugs URL](https://github.com/yorkshirelandscape/token_frames/issues)
Token Variant Art v4.62.4 [Bugs URL](https://github.com/Aedif/TokenVariants/issues)
TouchVTT v1.11.0 [Bugs URL](https://github.com/Oromis/touch-vtt/issues)
☯ Wheel Of Destiny v0.1.8

**Additional context**
Add any other context about the problem here (ex. any settings for Foundry, the System, and/or Modules that you think may be related).

If this could be solved with simply adding a condition to the data key line, that would be great but i suck at writing them.

**Comment by illandril** [comment]
Dynamic Tables are part of Custom System Builder, which doesn't currently work in Foundry v12, which is the only version of Foundry I'm actively supporting.

So, until that system works with v12 there won't be any progress on this. If you notice Custom System Builder has added support for v12, and this is still an issue in v12, feel free to comment here to make sure I'm aware that the system has been updated. I do not use that system, so I won't necessarily notice right away when it is updated.

**Comment by ghufufin** [comment]
Ok thanks for the reply and the information. I'll update the report if
anything changes.

**Comment by illandril** [comment]
@ghufufin I see two ways you might be setting up Tooltips to show Dynamic Tables...

1. Direct references to specific values (e.g. `system.props.table1.0.field1`, `system.props.table1.1.field1`, etc)
2. Referencing a label value that references a Dynamic Table (e.g. `system.props.label1`, where `label1` is configured as `${lookup('table1', 'field1')}$`)
3. Referencing the parent dynamic table value (e.g. `system.props.table1`)

With 1, there is absolutely no dynamic nature to the tooltip display. It shows the value you specify and only that value. Custom System Builder does soft-deletes, so if you delete a value from a table it is still in the table, just hidden from view, so any deleted values will still be accessible to the tooltip (because that value is still in the underlying data).

With 2, the tooltip seems to update as expected for my testing. This may have been something that was broken before but got fixed by something Custom System Builder changed in it's effort to support Foundry v12. If you are doing this, 

With 3, the tooltip won't show anything. Custom System Builder has an awkward structure to the underlying dynamic table data - any attempt at respecting this would be extremely fragile and very, very specific to this one system, so I don't want to add support for this structure.


So... whenever you upgrade toCustom System Builder v4.x, try option 2 for the lookup above (the Label can be set to have a Visibility formula of `false` if you don't want it to show in the tooltip but not on the character sheet).

If that doesn't work for you, feel free to re-open this issue - just export your templates JSON, the data for the actor you're using, and your Illandril's Token Tooltips Values and share them with me and I can take a closer look at specifically what you're trying to do.
