### ISSUE TITLE
Can't be installed on V11 and earlier

### ISSUE THREAD

**Issue by BoltsJ** [illandril/FoundryVTT-token-tooltips#102]
**Describe the bug**
On the foundry package listing, each version has the latest manifest linked. This prevents the module from being installed on v11, as it attempts to download the 4.0.0 release, which isn't compatible.

**What steps did you take before experiencing the problem?**
1. Install Foundry v11
2. Search for Illandril's Token Tooltips and see that it lists as version 3.10.3
3. Click install
4. Error message pops up: `module illandril-token-tooltips version 4.0.0 requires a more modern version of the Foundry Virtual Tabletop software: 12 or newer`

**What did you expect to happen?**
Version 3.10.3 of the module gets installed

**What happened instead?**
Foundry attempted and failed to install version 4.0.0

**Screenshots**
![image](https://github.com/illandril/FoundryVTT-token-tooltips/assets/182554/47dbe0fb-b406-43e0-81f0-d00134fb1e07)

![image](https://github.com/illandril/FoundryVTT-token-tooltips/assets/182554/1929b9e4-496b-461c-b2b1-4cb85df8f847)

**Foundry Versions**
 - Version of this module: 3.10.3. 4.0.0
 - Foundry Version: 11.315
 - System Name and Version: N/A
 - Browser Name and Version: Firefox

**What other modules did you have active when experiencing this issue (include both names and versions)?**
N/A

**Additional context**
Instead of the link to the latest module, the versioned releases in the foundry package listing should use the direct link to that version's manifest. Going in and editing the manifest url in the listing should be enough, because the individual manifests do correctly point to the versioned zip files. 

Example of my latest release for one of my modules
![image](https://github.com/illandril/FoundryVTT-token-tooltips/assets/182554/0259319f-c1dd-4a52-9ddb-a7167dc237fd)

**Comment by illandril** [comment]
At the time I set up the versions up this way, Foundry had the very annoying habit of warning you every time a manifest URL changed between versions, and making you confirm the change.

If I can confirm that the warning message is no longer there, then I will update this... but if the warning is still happening then I'd prefer to leave it as-is, because...
1. People update their modules much more frequently than the Foundry version change
2. That warning message is annoying and makes people less likely to update the module
3. Most people upgrade to the latest Foundry version too fast, not too slow, so most people won't experience this problem
4. There is a workaround - installing the module by manifest URL instead: https://github.com/illandril/FoundryVTT-token-tooltips/releases/download/v3.10.3/module.json

**Comment by BoltsJ** [comment]
I have done this for a while and have never seen that warning pop up for my modules.

**Comment by illandril** [comment]
![Screenshot 2024-06-05 204753](https://github.com/illandril/FoundryVTT-token-tooltips/assets/469205/e45c9da7-ca63-4953-9964-2f66e85d8aab)

Still happens. Both 6.0.0-beta2 and 6.0.0-beta3 of pf2e have the same manifest URL in the system.json, but Foundry shows a warning about it.

**Comment by BoltsJ** [comment]
https://foundryvtt.com/article/package-management/

![Screenshot_20240605-202014](https://github.com/illandril/FoundryVTT-token-tooltips/assets/182554/6a731480-1fa1-49b3-9b0b-291e61171bcf)


Official guidance recommends using the specific version.
