### ISSUE TITLE
Request: Show resources in tooltip

### ISSUE THREAD

**Issue by CeaneC** [illandril/FoundryVTT-token-tooltips#14]
Would it be possible to display Resources in the tooltip? It'd be useful for the Battle Master's superiority die and the Monk's ki points which don't have limited charges for individual features.

Excellent work on the module by the way, it's been really helpful!

**Comment by illandril** [comment]
It is possible, and I've put adding resources to the tooltip on my todo list, but I personally recommend using features to track Ki points, superiority die, etc..

For Ki, you give your character a feature called "Ki", give it an "Activation Cost" of "Special", and then give it the correct number of limited uses ("2 of 2 per Short Rest" for Ki at level 2). Then, for each of the individual Ki-consuming actions, you set the resource consumption to "Item Uses" and select "Ki" in the second dropdown (as opposed "Attributes" and the correct resource for resource-based consumption).

You can, of course, set up your character sheets whichever way you want, and I will be adding resources to the tooltip even if you say you don't need it anymore since there are definitely other scenarios where using Resources makes more sense than using Items / Features to track something.

**Comment by CeaneC** [comment]
Ah, I wasn't aware that other features came under item uses; that's helpful! Comes with the added bonus of being able to choose the icon too. I'll go with that implementation for now, but like you said I'm sure there'll be good uses for resources regardless
