### ISSUE TITLE
Add option to show tooltip only on PCs

### ISSUE THREAD

**Issue by ckdragons** [illandril/FoundryVTT-token-tooltips#35]
I use the Lite character sheets for NPCs, they don't have accurate information that is presented in the tooltip. Possible to add an option that shows the tooltips only for PCs? This would allow the GM to still the PCs tooltips but they wouldn't appear for NPCs.

**Comment by illandril** [comment]
What system and module is the Lite character sheet in?
What information isn't accurate?

**Comment by ckdragons** [comment]
Sorry for the misunderstanding. The Lite character sheet is a product of the PF1E game. The information isn't accurate because I don't include all the information on the character sheet when I build the actor/token (I use an outside method to track this information). So, there is nothing wrong with your module. I think it's a great module! My players are loving it, too!  :)

This was only to request to add an option to select which tokens the tooltip appears, PCs vs NPCs. My players love having the tooltips on their tokens. Whereas, I don't need them on the NPC tokens because I don't include all the information on their character sheet.

Again, sorry for the confusion. Hope it makes sense now.  :)

**Comment by illandril** [comment]
I am asking what information isn't accurate because I would prefer to selectively hide the inaccurate information, and only for the tokens that the information is inaccurate for, as opposed to having a blanket "hide everything for every NPC".

Looking at the PF1 Lite sheet, it appears that Health and Saving Throws should still be accurate, while AC, Perception, and Speeds will be wrong, and Immunities/Resistances/Vulnerabilities will never be specified so they should be blank anyway.
Is this correct?

Are you specifying Health and/or Saving Throws for your NPCs, or would these values be incorrect for you still even though they could be specified in the Lite sheet?

Do you have any custom tooltip values configured for PF1e?
Are any of them showing for NPCs where the details are inaccurate?
Do you think any of the custom tooltip values you have (accurate for NPCs or not) would be valuable for a large number of other PF1e groups?

**Comment by ckdragons** [comment]
Ah, now I understand that you are getting at. Thank you for clarifying and working with me on this.

I only currently only input the NPC's name, initiative, hp, size, and stature. The rest of the information I leave at default. Here is an example:
![image](https://user-images.githubusercontent.com/84493092/133107648-e7e28258-62a4-4d0f-9cdd-bfbd6a28c9ed.png)

I'm not using any custom tooltip values.
![image](https://user-images.githubusercontent.com/84493092/133109066-16397b45-8800-40bb-9219-eb83fc47d4a3.png)

I was previously using a number of custom tooltips, including listing the different movements. But I just now tested enabling this default value and see that you know include that information using the default Speed option. Maybe if you were to include Fly Maneuverability if the actor has a Fly speed?

Beyond that, this is a great module to have! Thank you for all your work and effort!
