### ISSUE TITLE
Data path with hyphen

### ISSUE THREAD

**Issue by jbhuddleston** [illandril/FoundryVTT-token-tooltips#59]
In GRPGA and associated projects which are almost completely item-based, I dynamically create a reference data structure in prepareDerivedData. I employ a slugified approach to naming entries in my data paths and that puts a lot of hyphens in those names.
The data path 
    data.dynamic["acrobatics-ranks"].value 
should be valid if you cannot find a way to support 
    data.dynamic.acrobatics-ranks.value

Thank you for making this excellent module by the way :-)

**Comment by illandril** [comment]
This will be difficult to do without either hindering performance, usability, and/or security for everyone who doesn't need support for properties with hyphens (or other characters that don't. I can look into it, but this probably won't be something I'll implement soon.


How difficult would it be for GRPGA to use underscores instead of hyphens for its slugs? Would just changing slugify from `-` to `_` be enough to change the format, or are there lots of other external dependencies on the slug format?

If that is an easy change, then that would probably be best since that would also ensure GRPGA is compatible with anything else that only works with property keys that don't need to be quoted.

**Comment by jbhuddleston** [comment]
That makes sense. I will look into it. Thank you. 
James

**Comment by jbhuddleston** [comment]
I have implemented the change to underscores as you suggested. It is much easier to work with now but was painful in transition. I don't think there is a need for this enhancement anymore.
